manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mylifeislifo
      url-base: https://github.com/mylifeislifo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: prospector-zmk-module
      remote: mylifeislifo
      revision: main
  self:
    path: config
